### ISSUE TITLE
Download button on website is broken

### ISSUE THREAD

**Issue by krisl21** [phoenixlauncher/phoenix#103]
Triggers an error: Uncaught (in promise) ReferenceError: url is not defined

**Comment by Shock9616** [comment]
@jxhug You said that the urls are being automatically grabbed from `appcast.xml` right? The link there (https://github.com/phoenixlauncher/phoenix/releases/download/v0.1.2-beta/Phoenix.dmg) is valid so something in your button code isn't working right

**Comment by jxhug** [comment]
will look

**Comment by jxhug** [comment]
fixed
