### ISSUE TITLE
Make better use of space in the detail view

### ISSUE THREAD

**Issue by Shock9616** [phoenixlauncher/phoenix#107]
<img width="1355" alt="Screenshot 2024-01-16 at 6 55 38 PM" src="https://github.com/phoenixlauncher/phoenix/assets/28808006/2907312f-ae99-4799-9b1c-3ad6a72d5fbe">
Something that's been bugging me for a while is the large amount of empty space in the detail view, as seen above. Different games suffer from this issue differently, mostly based on how long the description is, but it's annoying enough to me that I think it should be dealt with<br><br>

My proposed solution (there could be alternatives) is to make the description dynamically grow and shrink horizontally so that horizontal space is fully used, to lock its height to a small number of lines (and add a more button similar to reviews in the app store), and add a screenshots carousel underneath the description to use up the vertical space left there. See the below mock-up

<img width="1355" alt="Screenshot 2024-01-16 at 7 02 15 PM" src="https://github.com/phoenixlauncher/phoenix/assets/28808006/95351da3-5cc9-4cdd-9cbe-3e23fa632cdb">

Images could be filled in with the extra screenshots on IGDB with the option to add more or replace them with the user's own screenshots

**Comment by jxhug** [comment]
- [x] get screenshots to show
- [x] scroll on screenshots
- [ ] customizability of screenshot size in settings
- [ ] fade screenshots into the edge towards stats
- [ ] add implementation of custom user-uploaded screenshots

**Comment by jxhug** [comment]
DONE #147
