### ISSUE TITLE
The update is improperly signed and could not be validated. Please try again later or contact the app developer.

### ISSUE THREAD

**Issue by krisl21** [phoenixlauncher/phoenix#123]
When trying to update.

**Comment by Shock9616** [comment]
Thanks for the issue! We spent like 2 hours last night trying to fix this issue and ended up having to leave it for later. Hopefully it'll be fixed sometime today but for now, downloading from the releases page will still work

**Comment by jxhug** [comment]
fixed by running `./sign_updates` and giving dmg
