### ISSUE TITLE
Unable to Check For Updates

### ISSUE THREAD

**Issue by Shock9616** [phoenixlauncher/phoenix#124]
<img width="372" alt="Screenshot 2024-01-22 at 6 34 51 PM" src="https://github.com/phoenixlauncher/phoenix/assets/28808006/8a50cd75-315e-440d-8fad-60b745336f18">

When automatically checking for updates, this error will occur and the "Check for updates" button in the menu bar will be greyed out. We are working to isolate the problem and fix it ASAP

**Comment by jxhug** [comment]
only in xcode btw

**Comment by jxhug** [comment]
more documentation here: https://github.com/sparkle-project/Sparkle/issues/2497

**Comment by jxhug** [comment]
fixed in https://github.com/phoenixlauncher/phoenix/commit/25ed3e3e5ff9cc1c028dc91a3473228cbda3c554
