### ISSUE TITLE
separate platforms and stores

### ISSUE THREAD

**Issue by jxhug** [phoenixlauncher/phoenix#125]
maybe platforms is just macOS, pc, iOS, ps, xbox, nintendo
and stores is just steam, gog, epic

idk this is just a thought

**Comment by Shock9616** [comment]
How would this work for sorting? Since the stores are only available on macOS and PC and they're only used for sorting the list, it just seems to me like we'd be adding more complexity for no reason

**Comment by jxhug** [comment]
i think this is sort of similar to #82 and i'm going to close this in favor of that
