### ISSUE TITLE
Genre & Description Edits

### ISSUE THREAD

**Issue by esrasutton** [phoenixlauncher/phoenix#127]
I fetched metadata for a game, then tried to edit its genres. But the genre edits the description and vice versa.  The edit pop-up doesn't show the genres fetched. It displays duplicates of the game description.

**Comment by Shock9616** [comment]
https://github.com/phoenixlauncher/phoenix/assets/28808006/32ae4377-ebe3-4e66-9f5d-7d4c6821eb31

Video example, note that the genre does not actually get changed, it only changes what is shown in the text box

**Comment by Shock9616** [comment]
Fixed in [9cc672b](https://github.com/phoenixlauncher/phoenix/commit/9cc672b1886a4fe39a96f6a673617541b03acaad)
