### ISSUE TITLE
Game descriptions not being fetched

### ISSUE THREAD

**Issue by Shock9616** [phoenixlauncher/phoenix#130]
I just noticed that games' descriptions are not being fetched either automatically when games are added, or when I click "Fetch Metadata" on the edit page. All the other metadata is being fetched fine so I suspect it's just a typo, I just haven't found it yet.

**Comment by jxhug** [comment]
interesting, I'll have a look at the db

**Comment by Shock9616** [comment]
Just looking through `SupabaseViewModel` and have found that for whatever reason, this block of code in `convertSupabaseGame` is falling all the way back to the `?? ""` at the end:
```swift
if let storyline = supabaseGame.storyline, storyline.count < 1500, storyline != "" {
    game.metadata["description"] = storyline
} else {
    game.metadata["description"] = supabaseGame.summary ?? ""
}
```
I put the word "Test" in that string and that was added as the description when fetching metadata.

Is there something that has been changed in Supabase so that storyline and/or summary aren't valid anymore?

**Comment by jxhug** [comment]
hm alright I'll have a look sometime soon

**Comment by jxhug** [comment]
db issue, will be fixed by the end of the day
