### ISSUE TITLE
on json read convert old json syntax to new syntax

### ISSUE THREAD

**Issue by jxhug** [PhoenixLauncher/Phoenix#45]

**Comment by jxhug** [comment]
tasks are:

- [x] `isDeleted` to `is_deleted`
- [x] `platform.EMUL` to 'platform.NONE`

please comment with any more

**Comment by Shock9616** [comment]
Maybe add a check to make sure that the `appID` and `isDeleted` options actually exist as well? Just in case anyone jumped in on this update after staying on alpha 1 this whole time or something. Probably wouldn't be an issue, but better safe than sorry imo
