### ISSUE TITLE
revamp automatic detection

### ISSUE THREAD

**Issue by Shock9616** [phoenixlauncher/phoenix#50]
The list of platforms to add automatic detection for

- [ ] GOG
- [ ] Epic Games
- [x] CrossOver
- [ ] Parallels

Also add the ability to choose a non-standard path where games are stored

- [x] Add custom paths

**Comment by jxhug** [comment]
I think you should also let people choose a path to check. I install all my games on an external SSD so the autodetector never finds them :(

**Comment by jxhug** [comment]
also fix detection of false games such as
"Steamworks Common Redistributables"
"Unknown"

**Comment by jxhug** [comment]
custom steam path done in #79

**Comment by jxhug** [comment]
crossover support in #81

**Comment by Shock9616** [comment]
Man feels good to have this one done 😅
