### ISSUE TITLE
after game is saved redirect to game in detail view

### ISSUE THREAD

**Issue by jxhug** [phoenixlauncher/phoenix#64]
Right now if a game's name is changed the game detail view will still be trying to view the old game after it's saved, causing a blank screen.

**Comment by jxhug** [comment]
(may just be on the igdb branch)

**Comment by Shock9616** [comment]
Not just on the igdb branch. This also occurs on the latest release

**Comment by jxhug** [comment]
interestingly enough, this only happens when the igdb api is fetched from.

**Comment by jxhug** [comment]
fixed in #85
