### ISSUE TITLE
sidebar icon doesn't refresh after being changed

### ISSUE THREAD

**Issue by jxhug** [phoenixlauncher/phoenix#65]
this might only be on my igdb branch, but honestly not sure

**Comment by Shock9616** [comment]
That does appear to be the case. The icon refreshes just fine on the latest release

**Comment by jxhug** [comment]
ideas to debug:
* check whether the icon is refreshed when the game is saved or when the icon is inputted to test whether it's updating in the save or the import method

**Comment by jxhug** [comment]
tested the latest release (v0.0.8) on a school computer lol
the icon is refreshed upon being imported, meaning it doesn't have to do with the saving of games but rather the caching on images.
the header is also refreshed when the image is imported. the issue must've come when I refactored the image saving methods in `ImageUtils.swift`.

**Comment by jxhug** [comment]
done in igdb

**Comment by jxhug** [comment]
merged in #76
